# Generated by Django 4.2.4 on 2023-09-28 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_and_perms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('lastname', models.CharField(max_length=100, verbose_name='Lastname')),
                ('address', models.TextField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField(verbose_name='Birthday')),
            ],
        ),
    ]
