# Generated by Django 4.2.4 on 2023-09-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
